// Register + Login

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'


// Alertas

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'


// Agregar y Obtener Proyectos

export const MOSTRAR_FORMULARIO = 'MOSTRAR_FORMULARIO'
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS'
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const PROYECTO_ERROR = 'PROYECTO_ERROR'
export const OBTENER_CATEGORY = 'OBTENER_CATEGORY'


// Agregar y Obtener Jobs

export const AGREGAR_JOBS = 'AGREGAR_JOBS'
export const OBTENER_JOBS = 'OBTENER_JOBS'
export const ELIMINAR_JOBS = 'ELIMINAR_JOBS'
export const EDITAR_JOB = 'EDITAR_JOB'
export const JOB_ACTUAL = 'JOB_ACTUAL'
export const JOB_ERROR = 'JOB_ERROR'
